#!/bin/bash

# Copyright 2013-2014 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Amazon Software License (the "License"). You may not use this file except in compliance with the
# License. A copy of the License is located at
#
# http://aws.amazon.com/asl/
#
# or in the "LICENSE.txt" file accompanying this file. This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES 
# OR CONDITIONS OF ANY KIND, express or implied. See the License for the specific language governing permissions and
# limitations under the License.

set -x

. /opt/cfncluster/cfnconfig

# Source functions
. ../functions.shlib

function error_exit () {
  script=`basename $0`
  echo "cfncluster: $script - $1"
  logger -t cfncluster "$script - $1"
  exit 1
}

# Check FQDN dns
check_dns_fqdn || error_exit "FQDN DNS checks failed."


if [ "x$cfn_master" == "x" ]; then
  error_exit 'No master server specified.'
  usage
fi

myhostname=$(hostname -s)
if [ $? != 0 ]; then
  error_exit 'Failed to determine short hostname.'
fi

# Mount SGE NFS exports
function mount_nfs () {
RC=0
echo "$cfn_master:/opt/sge /opt/sge nfs hard,intr,noatime,vers=3,_netdev 0 0" >> /etc/fstab || RC=1
mount -v /opt/sge || RC=1
if [ $RC -ne 0 ]; then
  error_exit "Failed during during SGE NFS mounts"
fi
}

# Setup sge profile
function setup_sge_profile () {
RC=0
ln -s /opt/sge/default/common/settings.sh /etc/profile.d/sge.sh || RC=1
ln -s /opt/sge/default/common/settings.csh /etc/profile.d/sge.csh || RC=1
if [ $RC -ne 0 ]; then
  error_exit "Failed during SGE profile setup"
fi
}

function do_install () {
  mount_nfs
  setup_sge_profile
}

## Main script
do_install
  

script=`basename $0`
echo "cfncluster: $script - SUCCESS - Booted as cfncluster Compute connected to Master - $cfn_master"
logger -t cfncluster "$script - SUCCESS - Booted as cfncluster Compute connected to Master - $cfn_master"
