#!/bin/bash

# Copyright 2013-2014 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Amazon Software License (the "License"). You may not use this file except in compliance with the
# License. A copy of the License is located at
#
# http://aws.amazon.com/asl/
#
# or in the "LICENSE.txt" file accompanying this file. This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES 
# OR CONDITIONS OF ANY KIND, express or implied. See the License for the specific language governing permissions and
# limitations under the License.

set -x

# Source cfncluster config
. /opt/cfncluster/cfnconfig

# Source functions
. ../functions.shlib

function error_exit () {
  script=`basename $0`
  echo "cfncluster: $script - $1"
  logger -t cfncluster "$script - $1" 
  exit 1
}

# Check FQDN dns
check_dns_fqdn || error_exit "FQDN DNS checks failed."

myhostname=$(hostname -s)
if [ $? != 0 ]; then
  error_exit 'Failed to determine local hostname'
fi

# Setup SGE config as Master
function setup_master_sge () {
RC=0
cd /opt/sge || RC=1
./inst_sge -m -auto /opt/cfncluster/templates/sge/sge_inst.conf || RC=1
ln -s /opt/sge/default/common/settings.sh /etc/profile.d/sge.sh || RC=1
ln -s /opt/sge/default/common/settings.csh /etc/profile.d/sge.csh || RC=1
if [ $RC -ne 0 ]; then
  error_exit "Failed to configure SGE"
fi
}

# Start SGE
function start_sge () {
RC=0
chkconfig sgemaster.p6444 on || RC=1
service sgemaster.p6444 start || RC=1
if [ $RC -ne 0 ]; then
  error_exit "Failed to start SGE"
fi
}

# Add master as submit host
function add_master_submit () {
RC=0
. /opt/sge/default/common/settings.sh
qconf -as $myhostname || RC=1
if [ $RC -ne 0 ]; then
  error_exit "Failed to add $myhostname as submit host"
fi
}

# Adding custom CloudWatch metric to crontab
function add_custom_metric () {
RC=0
crontab -l > /tmp/root.crontab
echo "* * * * * /opt/cfncluster/scripts/sge/publish_pending_jobs.sh 2>&1" >> /tmp/root.crontab || RC=1
crontab /tmp/root.crontab || RC=1
if [ $RC -ne 0 ]; then
  error_exit "Failed to add custom metric crontab"
fi
}

function do_install () {
  setup_master_sge
  start_sge
  add_master_submit
  add_custom_metric
}

## Main script
do_install

script=`basename $0`
echo "cfncluster: $script - SUCCESS - Booted as cfncluster Master"
logger -t cfncluster "$script - SUCCESS - Booted as cfncluster Master"
