# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from pcluster.api import util
from pcluster.api.models.alarm_state import AlarmState  # noqa: E501
from pcluster.api.models.base_model_ import Model


class Alarm(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, alarm_type=None, alarm_state=None):  # noqa: E501
        """Alarm - a model defined in OpenAPI

        :param alarm_type: The alarm_type of this Alarm.  # noqa: E501
        :type alarm_type: str
        :param alarm_state: The alarm_state of this Alarm.  # noqa: E501
        :type alarm_state: AlarmState
        """
        self.openapi_types = {"alarm_type": str, "alarm_state": AlarmState}

        self.attribute_map = {"alarm_type": "alarmType", "alarm_state": "alarmState"}

        self._alarm_type = alarm_type
        self._alarm_state = alarm_state

    @classmethod
    def from_dict(cls, dikt) -> "Alarm":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Alarm of this Alarm.  # noqa: E501
        :rtype: Alarm
        """
        return util.deserialize_model(dikt, cls)

    @property
    def alarm_type(self):
        """Gets the alarm_type of this Alarm.

        The alarm type.  # noqa: E501

        :return: The alarm_type of this Alarm.
        :rtype: str
        """
        return self._alarm_type

    @alarm_type.setter
    def alarm_type(self, alarm_type):
        """Sets the alarm_type of this Alarm.

        The alarm type.  # noqa: E501

        :param alarm_type: The alarm_type of this Alarm.
        :type alarm_type: str
        """

        self._alarm_type = alarm_type

    @property
    def alarm_state(self):
        """Gets the alarm_state of this Alarm.


        :return: The alarm_state of this Alarm.
        :rtype: AlarmState
        """
        return self._alarm_state

    @alarm_state.setter
    def alarm_state(self, alarm_state):
        """Sets the alarm_state of this Alarm.


        :param alarm_state: The alarm_state of this Alarm.
        :type alarm_state: AlarmState
        """

        self._alarm_state = alarm_state
