# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from pcluster.api.models.base_model_ import Model
from pcluster.api.models.instance_state import InstanceState
from pcluster.api.models.node_type import NodeType
from pcluster.api import util

from pcluster.api.models.instance_state import InstanceState  # noqa: E501
from pcluster.api.models.node_type import NodeType  # noqa: E501

class ClusterInstance(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, instance_id=None, instance_type=None, launch_time=None, private_ip_address=None, public_ip_address=None, state=None, node_type=None, queue_name=None):  # noqa: E501
        """ClusterInstance - a model defined in OpenAPI

        :param instance_id: The instance_id of this ClusterInstance.  # noqa: E501
        :type instance_id: str
        :param instance_type: The instance_type of this ClusterInstance.  # noqa: E501
        :type instance_type: str
        :param launch_time: The launch_time of this ClusterInstance.  # noqa: E501
        :type launch_time: datetime
        :param private_ip_address: The private_ip_address of this ClusterInstance.  # noqa: E501
        :type private_ip_address: str
        :param public_ip_address: The public_ip_address of this ClusterInstance.  # noqa: E501
        :type public_ip_address: str
        :param state: The state of this ClusterInstance.  # noqa: E501
        :type state: InstanceState
        :param node_type: The node_type of this ClusterInstance.  # noqa: E501
        :type node_type: NodeType
        :param queue_name: The queue_name of this ClusterInstance.  # noqa: E501
        :type queue_name: str
        """
        self.openapi_types = {
            'instance_id': str,
            'instance_type': str,
            'launch_time': datetime,
            'private_ip_address': str,
            'public_ip_address': str,
            'state': InstanceState,
            'node_type': NodeType,
            'queue_name': str
        }

        self.attribute_map = {
            'instance_id': 'instanceId',
            'instance_type': 'instanceType',
            'launch_time': 'launchTime',
            'private_ip_address': 'privateIpAddress',
            'public_ip_address': 'publicIpAddress',
            'state': 'state',
            'node_type': 'nodeType',
            'queue_name': 'queueName'
        }

        self._instance_id = instance_id
        self._instance_type = instance_type
        self._launch_time = launch_time
        self._private_ip_address = private_ip_address
        self._public_ip_address = public_ip_address
        self._state = state
        self._node_type = node_type
        self._queue_name = queue_name

    @classmethod
    def from_dict(cls, dikt) -> 'ClusterInstance':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ClusterInstance of this ClusterInstance.  # noqa: E501
        :rtype: ClusterInstance
        """
        return util.deserialize_model(dikt, cls)

    @property
    def instance_id(self):
        """Gets the instance_id of this ClusterInstance.


        :return: The instance_id of this ClusterInstance.
        :rtype: str
        """
        return self._instance_id

    @instance_id.setter
    def instance_id(self, instance_id):
        """Sets the instance_id of this ClusterInstance.


        :param instance_id: The instance_id of this ClusterInstance.
        :type instance_id: str
        """
        if instance_id is None:
            raise ValueError("Invalid value for `instance_id`, must not be `None`")  # noqa: E501

        self._instance_id = instance_id

    @property
    def instance_type(self):
        """Gets the instance_type of this ClusterInstance.


        :return: The instance_type of this ClusterInstance.
        :rtype: str
        """
        return self._instance_type

    @instance_type.setter
    def instance_type(self, instance_type):
        """Sets the instance_type of this ClusterInstance.


        :param instance_type: The instance_type of this ClusterInstance.
        :type instance_type: str
        """
        if instance_type is None:
            raise ValueError("Invalid value for `instance_type`, must not be `None`")  # noqa: E501

        self._instance_type = instance_type

    @property
    def launch_time(self):
        """Gets the launch_time of this ClusterInstance.


        :return: The launch_time of this ClusterInstance.
        :rtype: datetime
        """
        return self._launch_time

    @launch_time.setter
    def launch_time(self, launch_time):
        """Sets the launch_time of this ClusterInstance.


        :param launch_time: The launch_time of this ClusterInstance.
        :type launch_time: datetime
        """
        if launch_time is None:
            raise ValueError("Invalid value for `launch_time`, must not be `None`")  # noqa: E501

        self._launch_time = launch_time

    @property
    def private_ip_address(self):
        """Gets the private_ip_address of this ClusterInstance.


        :return: The private_ip_address of this ClusterInstance.
        :rtype: str
        """
        return self._private_ip_address

    @private_ip_address.setter
    def private_ip_address(self, private_ip_address):
        """Sets the private_ip_address of this ClusterInstance.


        :param private_ip_address: The private_ip_address of this ClusterInstance.
        :type private_ip_address: str
        """
        if private_ip_address is None:
            raise ValueError("Invalid value for `private_ip_address`, must not be `None`")  # noqa: E501

        self._private_ip_address = private_ip_address

    @property
    def public_ip_address(self):
        """Gets the public_ip_address of this ClusterInstance.


        :return: The public_ip_address of this ClusterInstance.
        :rtype: str
        """
        return self._public_ip_address

    @public_ip_address.setter
    def public_ip_address(self, public_ip_address):
        """Sets the public_ip_address of this ClusterInstance.


        :param public_ip_address: The public_ip_address of this ClusterInstance.
        :type public_ip_address: str
        """

        self._public_ip_address = public_ip_address

    @property
    def state(self):
        """Gets the state of this ClusterInstance.


        :return: The state of this ClusterInstance.
        :rtype: InstanceState
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this ClusterInstance.


        :param state: The state of this ClusterInstance.
        :type state: InstanceState
        """
        if state is None:
            raise ValueError("Invalid value for `state`, must not be `None`")  # noqa: E501

        self._state = state

    @property
    def node_type(self):
        """Gets the node_type of this ClusterInstance.


        :return: The node_type of this ClusterInstance.
        :rtype: NodeType
        """
        return self._node_type

    @node_type.setter
    def node_type(self, node_type):
        """Sets the node_type of this ClusterInstance.


        :param node_type: The node_type of this ClusterInstance.
        :type node_type: NodeType
        """
        if node_type is None:
            raise ValueError("Invalid value for `node_type`, must not be `None`")  # noqa: E501

        self._node_type = node_type

    @property
    def queue_name(self):
        """Gets the queue_name of this ClusterInstance.


        :return: The queue_name of this ClusterInstance.
        :rtype: str
        """
        return self._queue_name

    @queue_name.setter
    def queue_name(self, queue_name):
        """Sets the queue_name of this ClusterInstance.


        :param queue_name: The queue_name of this ClusterInstance.
        :type queue_name: str
        """

        self._queue_name = queue_name
