# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from pcluster.api.models.base_model_ import Model
import re
from pcluster.api import util

import re  # noqa: E501

class CreateClusterRequestContent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, cluster_name=None, cluster_configuration=None):  # noqa: E501
        """CreateClusterRequestContent - a model defined in OpenAPI

        :param cluster_name: The cluster_name of this CreateClusterRequestContent.  # noqa: E501
        :type cluster_name: str
        :param cluster_configuration: The cluster_configuration of this CreateClusterRequestContent.  # noqa: E501
        :type cluster_configuration: str
        """
        self.openapi_types = {
            'cluster_name': str,
            'cluster_configuration': str
        }

        self.attribute_map = {
            'cluster_name': 'clusterName',
            'cluster_configuration': 'clusterConfiguration'
        }

        self._cluster_name = cluster_name
        self._cluster_configuration = cluster_configuration

    @classmethod
    def from_dict(cls, dikt) -> 'CreateClusterRequestContent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreateClusterRequestContent of this CreateClusterRequestContent.  # noqa: E501
        :rtype: CreateClusterRequestContent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cluster_name(self):
        """Gets the cluster_name of this CreateClusterRequestContent.

        Name of the cluster that will be created.  # noqa: E501

        :return: The cluster_name of this CreateClusterRequestContent.
        :rtype: str
        """
        return self._cluster_name

    @cluster_name.setter
    def cluster_name(self, cluster_name):
        """Sets the cluster_name of this CreateClusterRequestContent.

        Name of the cluster that will be created.  # noqa: E501

        :param cluster_name: The cluster_name of this CreateClusterRequestContent.
        :type cluster_name: str
        """
        if cluster_name is None:
            raise ValueError("Invalid value for `cluster_name`, must not be `None`")  # noqa: E501
        if cluster_name is not None and not re.search(r'^[a-zA-Z][a-zA-Z0-9-]+$', cluster_name):  # noqa: E501
            raise ValueError("Invalid value for `cluster_name`, must be a follow pattern or equal to `/^[a-zA-Z][a-zA-Z0-9-]+$/`")  # noqa: E501

        self._cluster_name = cluster_name

    @property
    def cluster_configuration(self):
        """Gets the cluster_configuration of this CreateClusterRequestContent.

        Cluster configuration as a YAML document.  # noqa: E501

        :return: The cluster_configuration of this CreateClusterRequestContent.
        :rtype: str
        """
        return self._cluster_configuration

    @cluster_configuration.setter
    def cluster_configuration(self, cluster_configuration):
        """Sets the cluster_configuration of this CreateClusterRequestContent.

        Cluster configuration as a YAML document.  # noqa: E501

        :param cluster_configuration: The cluster_configuration of this CreateClusterRequestContent.
        :type cluster_configuration: str
        """
        if cluster_configuration is None:
            raise ValueError("Invalid value for `cluster_configuration`, must not be `None`")  # noqa: E501

        self._cluster_configuration = cluster_configuration
