# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from pcluster.api.models.base_model_ import Model
from pcluster.api.models.compute_fleet_status import ComputeFleetStatus
from pcluster.api import util

from pcluster.api.models.compute_fleet_status import ComputeFleetStatus  # noqa: E501

class DescribeComputeFleetResponseContent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, status=None, last_status_updated_time=None):  # noqa: E501
        """DescribeComputeFleetResponseContent - a model defined in OpenAPI

        :param status: The status of this DescribeComputeFleetResponseContent.  # noqa: E501
        :type status: ComputeFleetStatus
        :param last_status_updated_time: The last_status_updated_time of this DescribeComputeFleetResponseContent.  # noqa: E501
        :type last_status_updated_time: datetime
        """
        self.openapi_types = {
            'status': ComputeFleetStatus,
            'last_status_updated_time': datetime
        }

        self.attribute_map = {
            'status': 'status',
            'last_status_updated_time': 'lastStatusUpdatedTime'
        }

        self._status = status
        self._last_status_updated_time = last_status_updated_time

    @classmethod
    def from_dict(cls, dikt) -> 'DescribeComputeFleetResponseContent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DescribeComputeFleetResponseContent of this DescribeComputeFleetResponseContent.  # noqa: E501
        :rtype: DescribeComputeFleetResponseContent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self):
        """Gets the status of this DescribeComputeFleetResponseContent.


        :return: The status of this DescribeComputeFleetResponseContent.
        :rtype: ComputeFleetStatus
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this DescribeComputeFleetResponseContent.


        :param status: The status of this DescribeComputeFleetResponseContent.
        :type status: ComputeFleetStatus
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def last_status_updated_time(self):
        """Gets the last_status_updated_time of this DescribeComputeFleetResponseContent.

        Timestamp representing the last status update time.  # noqa: E501

        :return: The last_status_updated_time of this DescribeComputeFleetResponseContent.
        :rtype: datetime
        """
        return self._last_status_updated_time

    @last_status_updated_time.setter
    def last_status_updated_time(self, last_status_updated_time):
        """Sets the last_status_updated_time of this DescribeComputeFleetResponseContent.

        Timestamp representing the last status update time.  # noqa: E501

        :param last_status_updated_time: The last_status_updated_time of this DescribeComputeFleetResponseContent.
        :type last_status_updated_time: datetime
        """

        self._last_status_updated_time = last_status_updated_time
