# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from pcluster.api.models.base_model_ import Model
from pcluster.api.models.cluster_instance import ClusterInstance
from pcluster.api import util

from pcluster.api.models.cluster_instance import ClusterInstance  # noqa: E501

class DescribeClusterInstancesResponseContent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, next_token=None, instances=None):  # noqa: E501
        """DescribeClusterInstancesResponseContent - a model defined in OpenAPI

        :param next_token: The next_token of this DescribeClusterInstancesResponseContent.  # noqa: E501
        :type next_token: str
        :param instances: The instances of this DescribeClusterInstancesResponseContent.  # noqa: E501
        :type instances: List[ClusterInstance]
        """
        self.openapi_types = {
            'next_token': str,
            'instances': List[ClusterInstance]
        }

        self.attribute_map = {
            'next_token': 'nextToken',
            'instances': 'instances'
        }

        self._next_token = next_token
        self._instances = instances

    @classmethod
    def from_dict(cls, dikt) -> 'DescribeClusterInstancesResponseContent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DescribeClusterInstancesResponseContent of this DescribeClusterInstancesResponseContent.  # noqa: E501
        :rtype: DescribeClusterInstancesResponseContent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def next_token(self):
        """Gets the next_token of this DescribeClusterInstancesResponseContent.

        Token to use for paginated requests.  # noqa: E501

        :return: The next_token of this DescribeClusterInstancesResponseContent.
        :rtype: str
        """
        return self._next_token

    @next_token.setter
    def next_token(self, next_token):
        """Sets the next_token of this DescribeClusterInstancesResponseContent.

        Token to use for paginated requests.  # noqa: E501

        :param next_token: The next_token of this DescribeClusterInstancesResponseContent.
        :type next_token: str
        """

        self._next_token = next_token

    @property
    def instances(self):
        """Gets the instances of this DescribeClusterInstancesResponseContent.


        :return: The instances of this DescribeClusterInstancesResponseContent.
        :rtype: List[ClusterInstance]
        """
        return self._instances

    @instances.setter
    def instances(self, instances):
        """Sets the instances of this DescribeClusterInstancesResponseContent.


        :param instances: The instances of this DescribeClusterInstancesResponseContent.
        :type instances: List[ClusterInstance]
        """
        if instances is None:
            raise ValueError("Invalid value for `instances`, must not be `None`")  # noqa: E501

        self._instances = instances
