# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from pcluster.api.models.base_model_ import Model
from pcluster.api.models.change import Change
from pcluster.api.models.config_validation_message import ConfigValidationMessage
from pcluster.api import util

from pcluster.api.models.change import Change  # noqa: E501
from pcluster.api.models.config_validation_message import ConfigValidationMessage  # noqa: E501

class DryrunOperationExceptionResponseContent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, message=None, change_set=None, validation_messages=None):  # noqa: E501
        """DryrunOperationExceptionResponseContent - a model defined in OpenAPI

        :param message: The message of this DryrunOperationExceptionResponseContent.  # noqa: E501
        :type message: str
        :param change_set: The change_set of this DryrunOperationExceptionResponseContent.  # noqa: E501
        :type change_set: List[Change]
        :param validation_messages: The validation_messages of this DryrunOperationExceptionResponseContent.  # noqa: E501
        :type validation_messages: List[ConfigValidationMessage]
        """
        self.openapi_types = {
            'message': str,
            'change_set': List[Change],
            'validation_messages': List[ConfigValidationMessage]
        }

        self.attribute_map = {
            'message': 'message',
            'change_set': 'changeSet',
            'validation_messages': 'validationMessages'
        }

        self._message = message
        self._change_set = change_set
        self._validation_messages = validation_messages

    @classmethod
    def from_dict(cls, dikt) -> 'DryrunOperationExceptionResponseContent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DryrunOperationExceptionResponseContent of this DryrunOperationExceptionResponseContent.  # noqa: E501
        :rtype: DryrunOperationExceptionResponseContent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self):
        """Gets the message of this DryrunOperationExceptionResponseContent.


        :return: The message of this DryrunOperationExceptionResponseContent.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this DryrunOperationExceptionResponseContent.


        :param message: The message of this DryrunOperationExceptionResponseContent.
        :type message: str
        """

        self._message = message

    @property
    def change_set(self):
        """Gets the change_set of this DryrunOperationExceptionResponseContent.

        List of configuration changes requested by the operation.  # noqa: E501

        :return: The change_set of this DryrunOperationExceptionResponseContent.
        :rtype: List[Change]
        """
        return self._change_set

    @change_set.setter
    def change_set(self, change_set):
        """Sets the change_set of this DryrunOperationExceptionResponseContent.

        List of configuration changes requested by the operation.  # noqa: E501

        :param change_set: The change_set of this DryrunOperationExceptionResponseContent.
        :type change_set: List[Change]
        """

        self._change_set = change_set

    @property
    def validation_messages(self):
        """Gets the validation_messages of this DryrunOperationExceptionResponseContent.

        List of messages collected during cluster config validation whose level is lower than the 'validationFailureLevel' set by the user.  # noqa: E501

        :return: The validation_messages of this DryrunOperationExceptionResponseContent.
        :rtype: List[ConfigValidationMessage]
        """
        return self._validation_messages

    @validation_messages.setter
    def validation_messages(self, validation_messages):
        """Sets the validation_messages of this DryrunOperationExceptionResponseContent.

        List of messages collected during cluster config validation whose level is lower than the 'validationFailureLevel' set by the user.  # noqa: E501

        :param validation_messages: The validation_messages of this DryrunOperationExceptionResponseContent.
        :type validation_messages: List[ConfigValidationMessage]
        """

        self._validation_messages = validation_messages
