# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from pcluster.api import util
from pcluster.api.models.base_model_ import Model
from pcluster.api.models.stack_event import StackEvent  # noqa: E501


class GetClusterStackEventsResponseContent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, next_token=None, events=None):  # noqa: E501
        """GetClusterStackEventsResponseContent - a model defined in OpenAPI

        :param next_token: The next_token of this GetClusterStackEventsResponseContent.  # noqa: E501
        :type next_token: str
        :param events: The events of this GetClusterStackEventsResponseContent.  # noqa: E501
        :type events: List[StackEvent]
        """
        self.openapi_types = {"next_token": str, "events": List[StackEvent]}

        self.attribute_map = {"next_token": "nextToken", "events": "events"}

        self._next_token = next_token
        self._events = events

    @classmethod
    def from_dict(cls, dikt) -> "GetClusterStackEventsResponseContent":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetClusterStackEventsResponseContent of this GetClusterStackEventsResponseContent.  # noqa: E501
        :rtype: GetClusterStackEventsResponseContent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def next_token(self):
        """Gets the next_token of this GetClusterStackEventsResponseContent.

        Token to use for paginated requests.  # noqa: E501

        :return: The next_token of this GetClusterStackEventsResponseContent.
        :rtype: str
        """
        return self._next_token

    @next_token.setter
    def next_token(self, next_token):
        """Sets the next_token of this GetClusterStackEventsResponseContent.

        Token to use for paginated requests.  # noqa: E501

        :param next_token: The next_token of this GetClusterStackEventsResponseContent.
        :type next_token: str
        """

        self._next_token = next_token

    @property
    def events(self):
        """Gets the events of this GetClusterStackEventsResponseContent.


        :return: The events of this GetClusterStackEventsResponseContent.
        :rtype: List[StackEvent]
        """
        return self._events

    @events.setter
    def events(self, events):
        """Sets the events of this GetClusterStackEventsResponseContent.


        :param events: The events of this GetClusterStackEventsResponseContent.
        :type events: List[StackEvent]
        """

        self._events = events
