# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from pcluster.api.models.base_model_ import Model
from pcluster.api import util


class ImageBuildStatus(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    BUILD_IN_PROGRESS = "BUILD_IN_PROGRESS"
    BUILD_FAILED = "BUILD_FAILED"
    BUILD_COMPLETE = "BUILD_COMPLETE"
    DELETE_IN_PROGRESS = "DELETE_IN_PROGRESS"
    DELETE_FAILED = "DELETE_FAILED"
    DELETE_COMPLETE = "DELETE_COMPLETE"
    def __init__(self):  # noqa: E501
        """ImageBuildStatus - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'ImageBuildStatus':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ImageBuildStatus of this ImageBuildStatus.  # noqa: E501
        :rtype: ImageBuildStatus
        """
        return util.deserialize_model(dikt, cls)
