# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from pcluster.api.models.base_model_ import Model
from pcluster.api import util


class ImageStatusFilteringOption(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    AVAILABLE = "AVAILABLE"
    PENDING = "PENDING"
    FAILED = "FAILED"
    def __init__(self):  # noqa: E501
        """ImageStatusFilteringOption - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'ImageStatusFilteringOption':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ImageStatusFilteringOption of this ImageStatusFilteringOption.  # noqa: E501
        :rtype: ImageStatusFilteringOption
        """
        return util.deserialize_model(dikt, cls)
