# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from pcluster.api.models.base_model_ import Model
from pcluster.api.models.image_info_summary import ImageInfoSummary
from pcluster.api import util

from pcluster.api.models.image_info_summary import ImageInfoSummary  # noqa: E501

class ListImagesResponseContent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, next_token=None, images=None):  # noqa: E501
        """ListImagesResponseContent - a model defined in OpenAPI

        :param next_token: The next_token of this ListImagesResponseContent.  # noqa: E501
        :type next_token: str
        :param images: The images of this ListImagesResponseContent.  # noqa: E501
        :type images: List[ImageInfoSummary]
        """
        self.openapi_types = {
            'next_token': str,
            'images': List[ImageInfoSummary]
        }

        self.attribute_map = {
            'next_token': 'nextToken',
            'images': 'images'
        }

        self._next_token = next_token
        self._images = images

    @classmethod
    def from_dict(cls, dikt) -> 'ListImagesResponseContent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ListImagesResponseContent of this ListImagesResponseContent.  # noqa: E501
        :rtype: ListImagesResponseContent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def next_token(self):
        """Gets the next_token of this ListImagesResponseContent.

        Token to use for paginated requests.  # noqa: E501

        :return: The next_token of this ListImagesResponseContent.
        :rtype: str
        """
        return self._next_token

    @next_token.setter
    def next_token(self, next_token):
        """Sets the next_token of this ListImagesResponseContent.

        Token to use for paginated requests.  # noqa: E501

        :param next_token: The next_token of this ListImagesResponseContent.
        :type next_token: str
        """

        self._next_token = next_token

    @property
    def images(self):
        """Gets the images of this ListImagesResponseContent.


        :return: The images of this ListImagesResponseContent.
        :rtype: List[ImageInfoSummary]
        """
        return self._images

    @images.setter
    def images(self, images):
        """Sets the images of this ListImagesResponseContent.


        :param images: The images of this ListImagesResponseContent.
        :type images: List[ImageInfoSummary]
        """
        if images is None:
            raise ValueError("Invalid value for `images`, must not be `None`")  # noqa: E501

        self._images = images
