# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from pcluster.api import util
from pcluster.api.models.base_model_ import Model
from pcluster.api.models.log_stream import LogStream  # noqa: E501


class ListImageLogStreamsResponseContent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, next_token=None, items=None):  # noqa: E501
        """ListImageLogStreamsResponseContent - a model defined in OpenAPI

        :param next_token: The next_token of this ListImageLogStreamsResponseContent.  # noqa: E501
        :type next_token: str
        :param items: The items of this ListImageLogStreamsResponseContent.  # noqa: E501
        :type items: List[LogStream]
        """
        self.openapi_types = {"next_token": str, "items": List[LogStream]}

        self.attribute_map = {"next_token": "nextToken", "items": "items"}

        self._next_token = next_token
        self._items = items

    @classmethod
    def from_dict(cls, dikt) -> "ListImageLogStreamsResponseContent":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ListImageLogStreamsResponseContent of this ListImageLogStreamsResponseContent.  # noqa: E501
        :rtype: ListImageLogStreamsResponseContent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def next_token(self):
        """Gets the next_token of this ListImageLogStreamsResponseContent.

        Token to use for paginated requests.  # noqa: E501

        :return: The next_token of this ListImageLogStreamsResponseContent.
        :rtype: str
        """
        return self._next_token

    @next_token.setter
    def next_token(self, next_token):
        """Sets the next_token of this ListImageLogStreamsResponseContent.

        Token to use for paginated requests.  # noqa: E501

        :param next_token: The next_token of this ListImageLogStreamsResponseContent.
        :type next_token: str
        """

        self._next_token = next_token

    @property
    def items(self):
        """Gets the items of this ListImageLogStreamsResponseContent.


        :return: The items of this ListImageLogStreamsResponseContent.
        :rtype: List[LogStream]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this ListImageLogStreamsResponseContent.


        :param items: The items of this ListImageLogStreamsResponseContent.
        :type items: List[LogStream]
        """
        if items is None:
            raise ValueError("Invalid value for `items`, must not be `None`")  # noqa: E501

        self._items = items
