# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from pcluster.api import util
from pcluster.api.models.base_model_ import Model


class RequestedComputeFleetStatus(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    START_REQUESTED = "START_REQUESTED"
    STOP_REQUESTED = "STOP_REQUESTED"
    ENABLED = "ENABLED"
    DISABLED = "DISABLED"
    def __init__(self):  # noqa: E501
        """RequestedComputeFleetStatus - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'RequestedComputeFleetStatus':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RequestedComputeFleetStatus of this RequestedComputeFleetStatus.  # noqa: E501
        :rtype: RequestedComputeFleetStatus
        """
        return util.deserialize_model(dikt, cls)
