# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from pcluster.api import util
from pcluster.api.models.base_model_ import Model


class Stat(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, stat_type=None, stat_value=None):  # noqa: E501
        """Stat - a model defined in OpenAPI

        :param stat_type: The stat_type of this Stat.  # noqa: E501
        :type stat_type: str
        :param stat_value: The stat_value of this Stat.  # noqa: E501
        :type stat_value: int
        """
        self.openapi_types = {"stat_type": str, "stat_value": int}

        self.attribute_map = {"stat_type": "statType", "stat_value": "statValue"}

        self._stat_type = stat_type
        self._stat_value = stat_value

    @classmethod
    def from_dict(cls, dikt) -> "Stat":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Stat of this Stat.  # noqa: E501
        :rtype: Stat
        """
        return util.deserialize_model(dikt, cls)

    @property
    def stat_type(self):
        """Gets the stat_type of this Stat.

        The metric type.  # noqa: E501

        :return: The stat_type of this Stat.
        :rtype: str
        """
        return self._stat_type

    @stat_type.setter
    def stat_type(self, stat_type):
        """Sets the stat_type of this Stat.

        The metric type.  # noqa: E501

        :param stat_type: The stat_type of this Stat.
        :type stat_type: str
        """

        self._stat_type = stat_type

    @property
    def stat_value(self):
        """Gets the stat_value of this Stat.

        The metric value.  # noqa: E501

        :return: The stat_value of this Stat.
        :rtype: int
        """
        return self._stat_value

    @stat_value.setter
    def stat_value(self, stat_value):
        """Sets the stat_value of this Stat.

        The metric value.  # noqa: E501

        :param stat_value: The stat_value of this Stat.
        :type stat_value: int
        """

        self._stat_value = stat_value
