# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from pcluster.api.models.base_model_ import Model
from pcluster.api import util


class ValidationLevel(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    def __init__(self):  # noqa: E501
        """ValidationLevel - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'ValidationLevel':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ValidationLevel of this ValidationLevel.  # noqa: E501
        :rtype: ValidationLevel
        """
        return util.deserialize_model(dikt, cls)
