#!/bin/bash

# Copyright 2013-2014 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Amazon Software License (the "License"). You may not use this file except in compliance with the
# License. A copy of the License is located at
#
# http://aws.amazon.com/asl/
#
# or in the "LICENSE.txt" file accompanying this file. This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES 
# OR CONDITIONS OF ANY KIND, express or implied. See the License for the specific language governing permissions and
# limitations under the License.

set -x

# Source cfncluster config
. /opt/cfncluster/cfnconfig

function error_exit () {
  script=`basename $0`
  echo "cfncluster: $script - $1"
  logger -t cfncluster "$script - $1" 
  exit 1
}

myhostname=$(hostname -s)
if [ $? != 0 ]; then
  error_exit 'Failed to determine local hostname'
fi

# Setup Torque on master
function setup_master_torque () {
RC=0
. /opt/cfncluster/templates/torque/torque.sh || RC=1
echo "/opt/torque/lib" >> /etc/ld.so.conf.d/torque.conf || RC=1
ldconfig || RC=1
cd /var/spool/torque || RC=1
/bin/cp -f /opt/cfncluster/templates/torque/server_name.MASTER server_name || RC=1
sed -i "s/<master>/$myhostname/" server_name || RC=1
chkconfig trqauthd on || RC=1
service trqauthd start || RC=1
cd /opt/cfncluster/scripts/torque || RC=1
./torque.setup root || RC=1
chkconfig pbs_server on || RC=1
service pbs_server restart || RC=1
chkconfig pbs_sched on || RC=1
service pbs_sched start || RC=1
cp /opt/cfncluster/templates/torque/torque.sh /etc/profile.d || RC=1
if [ $RC -ne 0 ]; then
  error_exit "Failed to configure Torque"
fi
}

# Adding custom CloudWatch metric to crontab
function add_custom_metric () {
RC=0
crontab -l > /tmp/root.crontab
echo "* * * * * /opt/cfncluster/scripts/torque/publish_pending_jobs.sh 2>&1" >> /tmp/root.crontab || RC=1
crontab /tmp/root.crontab || RC=1
if [ $RC -ne 0 ]; then
  error_exit "Failed to add custom metric crontab"
fi
}

function do_install () {
  setup_master_torque
  add_custom_metric
}

## Main script
do_install

script=`basename $0`
echo "cfncluster: $script - SUCCESS - Booted as cfncluster Master"
logger -t cfncluster "$script - SUCCESS - Booted as cfncluster Master"
