#!/bin/bash

# Copyright 2013-2014 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Amazon Software License (the "License"). You may not use this file except in compliance with the
# License. A copy of the License is located at
#
# http://aws.amazon.com/asl/
#
# or in the "LICENSE.txt" file accompanying this file. This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES 
# OR CONDITIONS OF ANY KIND, express or implied. See the License for the specific language governing permissions and
# limitations under the License.

set -x

. /opt/cfncluster/cfnconfig

function error_exit () {
  script=`basename $0`
  echo "cfncluster: $script - $1"
  logger -t cfncluster "$script - $1"
  exit 1
}

if [ "x$cfn_master" == "x" ]; then
  error_exit 'No master server specified.'
  usage
fi

myhostname=$(hostname -s)
if [ $? != 0 ]; then
  error_exit 'Failed to determine short hostname.'
fi

function setup_torque () {
RC=0
. /opt/cfncluster/templates/torque/torque.sh || RC=1
echo "/opt/torque/lib" >> /etc/ld.so.conf.d/torque.conf || RC=1
ldconfig || RC=1
cd /var/spool/torque || RC=1
/bin/cp -f /opt/cfncluster/templates/torque/server_name.COMPUTE server_name || RC=1
sed -i "s/<master>/$cfn_master/" server_name || RC=1
chkconfig trqauthd on || RC=1
service trqauthd start || RC=1
cd /var/spool/torque/mom_priv || RC=1
cp /opt/cfncluster/templates/torque/config.COMPUTE config || RC=1
sed -i "s/<master>/$cfn_master/" config || RC=1
chkconfig pbs_mom on || RC=1
service pbs_mom start || RC=1
cp /opt/cfncluster/templates/torque/torque.sh /etc/profile.d || RC=1
if [ $RC -ne 0 ]; then
  error_exit "Failed during during setup-torque"
fi
}

function do_install () {
  setup_torque
}

## Main script
do_install
  

script=`basename $0`
echo "cfncluster: $script - SUCCESS - Booted as cfncluster Compute connected to Master - $cfn_master"
logger -t cfncluster "$script - SUCCESS - Booted as cfncluster Compute connected to Master - $cfn_master"
