# Copyright 2021 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance
# with the License. A copy of the License is located at http://aws.amazon.com/apache2.0/
# or in the "LICENSE.txt" file accompanying this file. This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
# OR CONDITIONS OF ANY KIND, express or implied. See the License for the specific language governing permissions and
# limitations under the License.

# pylint: disable=R0801


from api import util
from api.models.base_model_ import Model


class ClusterConfigurationStructure(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, s3_url=None):
        """ClusterConfigurationStructure - a model defined in OpenAPI

        :param s3_url: The s3_url of this ClusterConfigurationStructure.
        :type s3_url: str
        """
        self.openapi_types = {"s3_url": str}

        self.attribute_map = {"s3_url": "s3Url"}

        self._s3_url = s3_url

    @classmethod
    def from_dict(cls, dikt) -> "ClusterConfigurationStructure":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ClusterConfigurationStructure of this ClusterConfigurationStructure.
        :rtype: ClusterConfigurationStructure
        """
        return util.deserialize_model(dikt, cls)

    @property
    def s3_url(self):
        """Gets the s3_url of this ClusterConfigurationStructure.

        S3 Url pointing to the cluster configuration file.

        :return: The s3_url of this ClusterConfigurationStructure.
        :rtype: str
        """
        return self._s3_url

    @s3_url.setter
    def s3_url(self, s3_url):
        """Sets the s3_url of this ClusterConfigurationStructure.

        S3 Url pointing to the cluster configuration file.

        :param s3_url: The s3_url of this ClusterConfigurationStructure.
        :type s3_url: str
        """

        self._s3_url = s3_url
