#!/bin/bash

# Copyright 2013-2014 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Amazon Software License (the "License"). You may not use this file except in compliance with the
# License. A copy of the License is located at
#
# http://aws.amazon.com/asl/
#
# or in the "LICENSE.txt" file accompanying this file. This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES 
# OR CONDITIONS OF ANY KIND, express or implied. See the License for the specific language governing permissions and
# limitations under the License.

set -x

. /opt/cfncluster/cfnconfig

function error_exit () {
  script=`basename $0`
  echo "cfncluster: $script - $1"
  logger -t cfncluster "$script - $1"
  exit 1
}

# Run preinstall script if defined
RC=0
if [ "${cfn_preinstall}" != "NONE" ]; then
  wget -qO- ${cfn_preinstall} | /bin/sh || RC=1
fi
if [ $RC -ne 0 ]; then
  error_exit "Failed to run boot_as_compute preinstall"
fi

# Run boot as compute for a specific scheduler
RC=0
/opt/cfncluster/scripts/${cfn_scheduler}/boot_as_compute >/var/log/cfncluster.log 2>&1 || RC=1
if [ $RC -ne 0 ]; then
  error_exit "Failed to run boot_as_compute for ${cfn_scheduler}"
fi

# Run postinstall script if defined
RC=0
if [ "${cfn_postinstall}" != "NONE" ]; then
  wget -qO- ${cfn_postinstall} | /bin/sh || RC=1
fi
if [ $RC -ne 0 ]; then
  error_exit "Failed to run boot_as_compute postinstall"
fi

# Notify compute is ready
instance_id_url="http://169.254.169.254/latest/meta-data/instance-id"
instance_id=$(curl --retry 3 --retry-delay 0 --silent --fail ${instance_id_url})
aws --region ${cfn_region} sqs send-message --queue-url ${cfn_sqs_url} --message-body '{"Type" : "Notification", "Message" : "{\"StatusCode\":\"Complete\",\"Description\":\"Succesfully launched '${instance_id}'\",\"Event\":\"cfncluster:COMPUTE_READY\",\"EC2InstanceId\":\"'${instance_id}'\"}"}'
