"""
    ParallelCluster

    ParallelCluster API  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from pcluster_client.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)

def lazy_import():
    from pcluster_client.model.cloud_formation_status import CloudFormationStatus
    from pcluster_client.model.cluster_configuration_structure import ClusterConfigurationStructure
    from pcluster_client.model.cluster_status import ClusterStatus
    from pcluster_client.model.compute_fleet_status import ComputeFleetStatus
    from pcluster_client.model.ec2_instance import EC2Instance
    from pcluster_client.model.tag import Tag
    globals()['CloudFormationStatus'] = CloudFormationStatus
    globals()['ClusterConfigurationStructure'] = ClusterConfigurationStructure
    globals()['ClusterStatus'] = ClusterStatus
    globals()['ComputeFleetStatus'] = ComputeFleetStatus
    globals()['EC2Instance'] = EC2Instance
    globals()['Tag'] = Tag


class DescribeClusterResponseContent(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
        ('cluster_name',): {
            'max_length': 60,
            'min_length': 5,
            'regex': {
                'pattern': r'^[a-zA-Z][a-zA-Z0-9-]+$',  # noqa: E501
            },
        },
    }

    additional_properties_type = None

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'creation_time': (datetime,),  # noqa: E501
            'version': (str,),  # noqa: E501
            'cluster_configuration': (ClusterConfigurationStructure,),  # noqa: E501
            'tags': ([Tag],),  # noqa: E501
            'cloud_formation_status': (CloudFormationStatus,),  # noqa: E501
            'cluster_name': (str,),  # noqa: E501
            'compute_fleet_status': (ComputeFleetStatus,),  # noqa: E501
            'cloudformation_stack_arn': (str,),  # noqa: E501
            'last_updated_time': (datetime,),  # noqa: E501
            'region': (str,),  # noqa: E501
            'cluster_status': (ClusterStatus,),  # noqa: E501
            'headnode': (EC2Instance,),  # noqa: E501
            'failure_reason': (str,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'creation_time': 'creationTime',  # noqa: E501
        'version': 'version',  # noqa: E501
        'cluster_configuration': 'clusterConfiguration',  # noqa: E501
        'tags': 'tags',  # noqa: E501
        'cloud_formation_status': 'cloudFormationStatus',  # noqa: E501
        'cluster_name': 'clusterName',  # noqa: E501
        'compute_fleet_status': 'computeFleetStatus',  # noqa: E501
        'cloudformation_stack_arn': 'cloudformationStackArn',  # noqa: E501
        'last_updated_time': 'lastUpdatedTime',  # noqa: E501
        'region': 'region',  # noqa: E501
        'cluster_status': 'clusterStatus',  # noqa: E501
        'headnode': 'headnode',  # noqa: E501
        'failure_reason': 'failureReason',  # noqa: E501
    }

    _composed_schemas = {}

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, creation_time, version, cluster_configuration, tags, cloud_formation_status, cluster_name, compute_fleet_status, cloudformation_stack_arn, last_updated_time, region, cluster_status, *args, **kwargs):  # noqa: E501
        """DescribeClusterResponseContent - a model defined in OpenAPI

        Args:
            creation_time (datetime): Timestamp representing the cluster creation time
            version (str): ParallelCluster version used to create the cluster
            cluster_configuration (ClusterConfigurationStructure):
            tags ([Tag]): Tags associated with the cluster
            cloud_formation_status (CloudFormationStatus):
            cluster_name (str): Name of the cluster
            compute_fleet_status (ComputeFleetStatus):
            cloudformation_stack_arn (str): ARN of the main CloudFormation stack
            last_updated_time (datetime): Timestamp representing the last cluster update time
            region (str): AWS region where the cluster is created
            cluster_status (ClusterStatus):

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            headnode (EC2Instance): [optional]  # noqa: E501
            failure_reason (str): Describe the reason of the failure when the stack is in CREATE_FAILED, UPDATE_FAILED or DELETE_FAILED status. [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.creation_time = creation_time
        self.version = version
        self.cluster_configuration = cluster_configuration
        self.tags = tags
        self.cloud_formation_status = cloud_formation_status
        self.cluster_name = cluster_name
        self.compute_fleet_status = compute_fleet_status
        self.cloudformation_stack_arn = cloudformation_stack_arn
        self.last_updated_time = last_updated_time
        self.region = region
        self.cluster_status = cluster_status
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
