AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.8

  Sample SAM Template for pcluster-lambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 256

Resources:
  ParallelClusterFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Events:
        ApiEvent:
          Type: HttpApi
    Metadata:
      Dockerfile: ../api/docker/awslambda/Dockerfile
      DockerContext: ../../../../cli
      DockerTag: pcluster-api-sam

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ParallelClusterFunction:
    Description: "ParallelCluster Lambda Function ARN"
    Value: !GetAtt ParallelClusterFunction.Arn
  ParallelClusterFunctionIamRole:
    Description: "Implicit IAM Role created for ParallelCluster function"
    Value: !GetAtt ParallelClusterFunctionRole.Arn
