#!/bin/bash

# Copyright 2013-2014 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Amazon Software License (the "License"). You may not use this file except in compliance with the
# License. A copy of the License is located at
#
# http://aws.amazon.com/asl/
#
# or in the "LICENSE.txt" file accompanying this file. This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES 
# OR CONDITIONS OF ANY KIND, express or implied. See the License for the specific language governing permissions and
# limitations under the License.

set -x

# Source cfncluster config
. /opt/cfncluster/cfnconfig

function error_exit () {
  script=`basename $0`
  echo "cfncluster: $script - $1"
  logger -t cfncluster "$script - $1"
  exit 1
}

myhostname=$(hostname -s)
if [ $? != 0 ]; then
  error_exit 'Failed to determine local hostname'
fi

# Setup openlava config as Master
function setup_master_openlava () {
RC=0
cd /opt/openlava-2.2/etc || RC=1
/bin/cp -f /opt/cfncluster/templates/openlava/lsf.conf.MASTER lsf.conf || RC=1
/bin/cp -f /opt/cfncluster/templates/openlava/lsf.cluster.openlava.MASTER lsf.cluster.openlava || RC=1
/bin/cp -f /opt/cfncluster/templates/openlava/lsb.hosts.MASTER lsb.hosts || RC=1
sed -i "s/<master>/$myhostname/" lsf.cluster.openlava || RC=1
sed -i "s/<master>/$myhostname/" lsb.hosts || RC=1
ln -s /opt/openlava-2.2/etc/openlava.sh /etc/profile.d/openlava.sh || RC=1
ln -s /opt/openlava-2.2/etc/openlava.csh /etc/profile.d/openlava.csh || RC=1
if [ $RC -ne 0 ]; then
  error_exit "Failed to configure Openlava"
fi
}

# Adding custom CloudWatch metric to crontab
function add_custom_metric () {
RC=0
crontab -l > /tmp/root.crontab
echo "* * * * * /opt/cfncluster/scripts/openlava/publish_pending_jobs.sh 2>&1" >> /tmp/root.crontab || RC=1
crontab /tmp/root.crontab || RC=1
if [ $RC -ne 0 ]; then
  error_exit "Failed to add custom metric crontab"
fi
}

# Start openlava
function start_openlava () {
RC=0
chkconfig openlava on || RC=1
service openlava start || RC=1
. /etc/profile.d/openlava.sh || RC=1
badmin hclose ${myhostname} || RC=1
if [ $RC -ne 0 ]; then
  error_exit "Failed to start Openlava"
fi
}

function minimal_install () {
  setup_master_openlava
  start_openlava
  add_custom_metric
}

## Main script
case $cfn_install_type in
  minimal)
    minimal_install
    ;;

  *)
    error_exit "Unkown install type: $cfn_install_type"

esac

script=`basename $0`
echo "cfncluster: $script - SUCCESS - Booted as cfncluster Master"
logger -t cfncluster "$script - SUCCESS - Booted as cfncluster Master"
