#!/bin/bash

# Copyright 2013-2014 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Amazon Software License (the "License"). You may not use this file except in compliance with the
# License. A copy of the License is located at
#
# http://aws.amazon.com/asl/
#
# or in the "LICENSE.txt" file accompanying this file. This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES 
# OR CONDITIONS OF ANY KIND, express or implied. See the License for the specific language governing permissions and
# limitations under the License.

set -x

. /opt/cfncluster/cfnconfig

function error_exit () {
  script=`basename $0`
  echo "cfncluster: $script - $1"
  logger -t cfncluster "$script - $1"
  exit 1
}

if [ "x$cfn_master" == "x" ]; then
  error_exit 'No master server specified.'
  usage
fi

myhostname=$(hostname -s)
if [ $? != 0 ]; then
  error_exit 'Failed to determine short hostname.'
fi

# Determine instance type
instance_type=`curl --retry 3 --retry-delay 0 --silent --fail http://169.254.169.254/latest/meta-data/instance-type`
instance_type=$(echo $instance_type| tr '.' '_')

# Setup resources
resources="cs $instance_type $cfn_resources"

# Configure openlava
function configure_openlava () {
RC=0
cd /opt/openlava-2.2/etc || RC=1
/bin/cp -f /opt/cfncluster/templates/openlava/lsf.conf.COMPUTE lsf.conf || RC=1
/bin/cp -f /opt/cfncluster/templates/openlava/lsf.cluster.openlava.COMPUTE lsf.cluster.openlava || RC=1
sed -i "s/<master>/$cfn_master/" lsf.conf || RC=1
sed -i "s/<master>/$cfn_master/" lsf.cluster.openlava || RC=1
sed -i "s/<compute>/$myhostname/" lsf.cluster.openlava || RC=1
ln -s /opt/openlava-2.2/etc/openlava.sh /etc/profile.d/openlava.sh || RC=1
ln -s /opt/openlava-2.2/etc/openlava.csh /etc/profile.d/openlava.csh || RC=1
if [ $RC -ne 0 ]; then
  error_exit "Failed during Openlava configuration"
fi
}

# Start openlava
function start_openlava () {
RC=0
chkconfig openlava on || RC=1
service openlava start || RC=1
if [ $RC -ne 0 ]; then
  error_exit "Failed to start openlava"
fi
}

function minimal_install () {
  configure_openlava
  start_openlava
}

## Main script
case $cfn_install_type in
  minimal)
    minimal_install
    ;;

  *)
    error_exit "Unkown install type: $cfn_install_type"

esac


script=`basename $0`
echo "cfncluster: $script - SUCCESS - Booted as cfncluster Compute connected to Master - $cfn_master"
logger -t cfncluster "$script - SUCCESS - Booted as cfncluster Compute connected to Master - $cfn_master"
