"""
    ParallelCluster

    ParallelCluster API  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pcluster.client
from pcluster.client.model.not_found_exception_response_content import NotFoundExceptionResponseContent


class TestNotFoundExceptionResponseContent(unittest.TestCase):
    """NotFoundExceptionResponseContent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNotFoundExceptionResponseContent(self):
        """Test NotFoundExceptionResponseContent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NotFoundExceptionResponseContent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
