"""
    ParallelCluster

    ParallelCluster API  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import pcluster.client
from pcluster.client.api.image_operations_api import ImageOperationsApi  # noqa: E501


class TestImageOperationsApi(unittest.TestCase):
    """ImageOperationsApi unit test stubs"""

    def setUp(self):
        self.api = ImageOperationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_build_image(self):
        """Test case for build_image

        """
        pass

    def test_delete_image(self):
        """Test case for delete_image

        """
        pass

    def test_describe_image(self):
        """Test case for describe_image

        """
        pass

    def test_describe_official_images(self):
        """Test case for describe_official_images

        """
        pass

    def test_list_images(self):
        """Test case for list_images

        """
        pass


if __name__ == '__main__':
    unittest.main()
