"""
    ParallelCluster

    ParallelCluster API  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pcluster.client
from pcluster.client.model.config_validation_message import ConfigValidationMessage
from pcluster.client.model.image_info_summary import ImageInfoSummary
globals()['ConfigValidationMessage'] = ConfigValidationMessage
globals()['ImageInfoSummary'] = ImageInfoSummary
from pcluster.client.model.build_image_response_content import BuildImageResponseContent


class TestBuildImageResponseContent(unittest.TestCase):
    """BuildImageResponseContent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBuildImageResponseContent(self):
        """Test BuildImageResponseContent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BuildImageResponseContent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
