"""
    ParallelCluster

    ParallelCluster API  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pcluster.client
from pcluster.client.model.config_validation_message import ConfigValidationMessage
globals()['ConfigValidationMessage'] = ConfigValidationMessage
from pcluster.client.model.create_cluster_bad_request_exception_response_content import CreateClusterBadRequestExceptionResponseContent


class TestCreateClusterBadRequestExceptionResponseContent(unittest.TestCase):
    """CreateClusterBadRequestExceptionResponseContent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateClusterBadRequestExceptionResponseContent(self):
        """Test CreateClusterBadRequestExceptionResponseContent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateClusterBadRequestExceptionResponseContent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
