"""
    ParallelCluster

    ParallelCluster API  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pcluster_client
from pcluster_client.model.log_stream import LogStream
globals()['LogStream'] = LogStream
from pcluster_client.model.list_cluster_log_streams_response_content import ListClusterLogStreamsResponseContent


class TestListClusterLogStreamsResponseContent(unittest.TestCase):
    """ListClusterLogStreamsResponseContent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListClusterLogStreamsResponseContent(self):
        """Test ListClusterLogStreamsResponseContent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListClusterLogStreamsResponseContent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
