"""
    ParallelCluster

    ParallelCluster API  # noqa: E501

    The version of the OpenAPI document: 3.7.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pcluster_client
from pcluster_client.model.stat import Stat


class TestStat(unittest.TestCase):
    """Stat unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStat(self):
        """Test Stat"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Stat()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
