"""
    ParallelCluster

    ParallelCluster API  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pcluster.client
from pcluster.client.model.cloud_formation_status import CloudFormationStatus
from pcluster.client.model.image_build_status import ImageBuildStatus
globals()['CloudFormationStatus'] = CloudFormationStatus
globals()['ImageBuildStatus'] = ImageBuildStatus
from pcluster.client.model.image_info_summary import ImageInfoSummary


class TestImageInfoSummary(unittest.TestCase):
    """ImageInfoSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testImageInfoSummary(self):
        """Test ImageInfoSummary"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ImageInfoSummary()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
