"""
    ParallelCluster

    ParallelCluster API  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pcluster_client
from pcluster_client.model.log_event import LogEvent
globals()['LogEvent'] = LogEvent
from pcluster_client.model.get_cluster_log_events_response_content import GetClusterLogEventsResponseContent


class TestGetClusterLogEventsResponseContent(unittest.TestCase):
    """GetClusterLogEventsResponseContent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetClusterLogEventsResponseContent(self):
        """Test GetClusterLogEventsResponseContent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetClusterLogEventsResponseContent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
