"""
    ParallelCluster

    ParallelCluster API  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pcluster.client
from pcluster.client.model.cluster_configuration_structure import ClusterConfigurationStructure


class TestClusterConfigurationStructure(unittest.TestCase):
    """ClusterConfigurationStructure unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClusterConfigurationStructure(self):
        """Test ClusterConfigurationStructure"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ClusterConfigurationStructure()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
