"""
    ParallelCluster

    ParallelCluster API  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import pcluster_client
from pcluster_client.api.cluster_logs_api import ClusterLogsApi  # noqa: E501


class TestClusterLogsApi(unittest.TestCase):
    """ClusterLogsApi unit test stubs"""

    def setUp(self):
        self.api = ClusterLogsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_cluster_log_events(self):
        """Test case for get_cluster_log_events

        """
        pass

    def test_get_cluster_stack_events(self):
        """Test case for get_cluster_stack_events

        """
        pass

    def test_list_cluster_log_streams(self):
        """Test case for list_cluster_log_streams

        """
        pass


if __name__ == '__main__':
    unittest.main()
