"""
    ParallelCluster

    ParallelCluster API  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pcluster_client
from pcluster_client.model.update_compute_fleet_response_content import UpdateComputeFleetResponseContent


class TestUpdateComputeFleetResponseContent(unittest.TestCase):
    """UpdateComputeFleetResponseContent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateComputeFleetResponseContent(self):
        """Test UpdateComputeFleetResponseContent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateComputeFleetResponseContent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
