"""
    ParallelCluster

    ParallelCluster API  # noqa: E501

    The version of the OpenAPI document: 3.7.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pcluster_client
from pcluster_client.model.alarm_state import AlarmState
globals()['AlarmState'] = AlarmState
from pcluster_client.model.alarm import Alarm


class TestAlarm(unittest.TestCase):
    """Alarm unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAlarm(self):
        """Test Alarm"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Alarm()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
