"""
    ParallelCluster

    ParallelCluster API  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pcluster.client
from pcluster.client.model.image_build_status import ImageBuildStatus


class TestImageBuildStatus(unittest.TestCase):
    """ImageBuildStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testImageBuildStatus(self):
        """Test ImageBuildStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ImageBuildStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
