"""
    ParallelCluster

    ParallelCluster API  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pcluster.client
from pcluster.client.model.requested_compute_fleet_status import RequestedComputeFleetStatus


class TestRequestedComputeFleetStatus(unittest.TestCase):
    """RequestedComputeFleetStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequestedComputeFleetStatus(self):
        """Test RequestedComputeFleetStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RequestedComputeFleetStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
