"""
    ParallelCluster

    ParallelCluster API  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pcluster.client
from pcluster.client.model.update_cluster_request_content import UpdateClusterRequestContent


class TestUpdateClusterRequestContent(unittest.TestCase):
    """UpdateClusterRequestContent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateClusterRequestContent(self):
        """Test UpdateClusterRequestContent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateClusterRequestContent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
