"""
    ParallelCluster

    ParallelCluster API  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pcluster.client
from pcluster.client.model.ec2_ami_state import Ec2AmiState
from pcluster.client.model.tag import Tag
globals()['Ec2AmiState'] = Ec2AmiState
globals()['Tag'] = Tag
from pcluster.client.model.ec2_ami_info import Ec2AmiInfo


class TestEc2AmiInfo(unittest.TestCase):
    """Ec2AmiInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEc2AmiInfo(self):
        """Test Ec2AmiInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Ec2AmiInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
