"""
    ParallelCluster

    ParallelCluster API  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pcluster_client
from pcluster_client.model.metadata import Metadata
globals()['Metadata'] = Metadata
from pcluster_client.model.scheduler import Scheduler


class TestScheduler(unittest.TestCase):
    """Scheduler unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScheduler(self):
        """Test Scheduler"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Scheduler()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
