"""
    ParallelCluster

    ParallelCluster API  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pcluster.client
from pcluster.client.model.unauthorized_client_error_response_content import UnauthorizedClientErrorResponseContent


class TestUnauthorizedClientErrorResponseContent(unittest.TestCase):
    """UnauthorizedClientErrorResponseContent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUnauthorizedClientErrorResponseContent(self):
        """Test UnauthorizedClientErrorResponseContent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UnauthorizedClientErrorResponseContent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
