"""
    ParallelCluster

    ParallelCluster API  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pcluster.client
from pcluster.client.model.image_info_summary import ImageInfoSummary
globals()['ImageInfoSummary'] = ImageInfoSummary
from pcluster.client.model.delete_image_response_content import DeleteImageResponseContent


class TestDeleteImageResponseContent(unittest.TestCase):
    """DeleteImageResponseContent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeleteImageResponseContent(self):
        """Test DeleteImageResponseContent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DeleteImageResponseContent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
