"""
    ParallelCluster

    ParallelCluster API  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pcluster.client
from pcluster.client.model.cluster_info_summary import ClusterInfoSummary
globals()['ClusterInfoSummary'] = ClusterInfoSummary
from pcluster.client.model.delete_cluster_response_content import DeleteClusterResponseContent


class TestDeleteClusterResponseContent(unittest.TestCase):
    """DeleteClusterResponseContent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeleteClusterResponseContent(self):
        """Test DeleteClusterResponseContent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DeleteClusterResponseContent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
