"""
    ParallelCluster

    ParallelCluster API  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pcluster.client
from pcluster.client.model.image_status_filtering_option import ImageStatusFilteringOption


class TestImageStatusFilteringOption(unittest.TestCase):
    """ImageStatusFilteringOption unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testImageStatusFilteringOption(self):
        """Test ImageStatusFilteringOption"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ImageStatusFilteringOption()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
