"""
    ParallelCluster

    ParallelCluster API  # noqa: E501

    The version of the OpenAPI document: 3.7.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pcluster_client
from pcluster_client.model.login_nodes_state import LoginNodesState
globals()['LoginNodesState'] = LoginNodesState
from pcluster_client.model.login_nodes_pool import LoginNodesPool


class TestLoginNodesPool(unittest.TestCase):
    """LoginNodesPool unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLoginNodesPool(self):
        """Test LoginNodesPool"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LoginNodesPool()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
