"""
    ParallelCluster

    ParallelCluster API  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pcluster.client
from pcluster.client.model.cluster_info_summary import ClusterInfoSummary
globals()['ClusterInfoSummary'] = ClusterInfoSummary
from pcluster.client.model.list_clusters_response_content import ListClustersResponseContent


class TestListClustersResponseContent(unittest.TestCase):
    """ListClustersResponseContent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListClustersResponseContent(self):
        """Test ListClustersResponseContent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListClustersResponseContent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
