"""
    ParallelCluster

    ParallelCluster API  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pcluster.client
from pcluster.client.model.compute_fleet_status import ComputeFleetStatus
globals()['ComputeFleetStatus'] = ComputeFleetStatus
from pcluster.client.model.describe_compute_fleet_status_response_content import DescribeComputeFleetStatusResponseContent


class TestDescribeComputeFleetStatusResponseContent(unittest.TestCase):
    """DescribeComputeFleetStatusResponseContent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDescribeComputeFleetStatusResponseContent(self):
        """Test DescribeComputeFleetStatusResponseContent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DescribeComputeFleetStatusResponseContent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
