"""
    ParallelCluster

    ParallelCluster API  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pcluster_client
from pcluster_client.model.ami_info import AmiInfo
globals()['AmiInfo'] = AmiInfo
from pcluster_client.model.list_official_images_response_content import ListOfficialImagesResponseContent


class TestListOfficialImagesResponseContent(unittest.TestCase):
    """ListOfficialImagesResponseContent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListOfficialImagesResponseContent(self):
        """Test ListOfficialImagesResponseContent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListOfficialImagesResponseContent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
