"""
    ParallelCluster

    ParallelCluster API  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pcluster.client
from pcluster.client.model.ami_info import AmiInfo
globals()['AmiInfo'] = AmiInfo
from pcluster.client.model.describe_official_images_response_content import DescribeOfficialImagesResponseContent


class TestDescribeOfficialImagesResponseContent(unittest.TestCase):
    """DescribeOfficialImagesResponseContent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDescribeOfficialImagesResponseContent(self):
        """Test DescribeOfficialImagesResponseContent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DescribeOfficialImagesResponseContent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
