"""
    ParallelCluster

    ParallelCluster API  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pcluster.client
from pcluster.client.model.bad_request_exception_response_content import BadRequestExceptionResponseContent


class TestBadRequestExceptionResponseContent(unittest.TestCase):
    """BadRequestExceptionResponseContent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBadRequestExceptionResponseContent(self):
        """Test BadRequestExceptionResponseContent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BadRequestExceptionResponseContent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
