"""
    ParallelCluster

    ParallelCluster API  # noqa: E501

    The version of the OpenAPI document: 3.7.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pcluster_client
from pcluster_client.model.metric import Metric


class TestMetric(unittest.TestCase):
    """Metric unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMetric(self):
        """Test Metric"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Metric()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
