"""
    ParallelCluster

    ParallelCluster API  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pcluster_client
from pcluster_client.model.log_stream import LogStream


class TestLogStream(unittest.TestCase):
    """LogStream unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLogStream(self):
        """Test LogStream"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LogStream()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
