"""
    ParallelCluster

    ParallelCluster API  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pcluster.client
from pcluster.client.model.ec2_instance import EC2Instance
globals()['EC2Instance'] = EC2Instance
from pcluster.client.model.describe_cluster_instances_response_content import DescribeClusterInstancesResponseContent


class TestDescribeClusterInstancesResponseContent(unittest.TestCase):
    """DescribeClusterInstancesResponseContent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDescribeClusterInstancesResponseContent(self):
        """Test DescribeClusterInstancesResponseContent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DescribeClusterInstancesResponseContent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
