"""
    ParallelCluster

    ParallelCluster API  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pcluster.client
from pcluster.client.model.requested_compute_fleet_status import RequestedComputeFleetStatus
globals()['RequestedComputeFleetStatus'] = RequestedComputeFleetStatus
from pcluster.client.model.update_compute_fleet_status_request_content import UpdateComputeFleetStatusRequestContent


class TestUpdateComputeFleetStatusRequestContent(unittest.TestCase):
    """UpdateComputeFleetStatusRequestContent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateComputeFleetStatusRequestContent(self):
        """Test UpdateComputeFleetStatusRequestContent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateComputeFleetStatusRequestContent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
