"""
    ParallelCluster

    ParallelCluster API  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pcluster_client
from pcluster_client.model.metadata import Metadata


class TestMetadata(unittest.TestCase):
    """Metadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMetadata(self):
        """Test Metadata"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Metadata()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
