"""
    ParallelCluster

    ParallelCluster API  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pcluster.client
from pcluster.client.model.internal_service_exception_response_content import InternalServiceExceptionResponseContent


class TestInternalServiceExceptionResponseContent(unittest.TestCase):
    """InternalServiceExceptionResponseContent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInternalServiceExceptionResponseContent(self):
        """Test InternalServiceExceptionResponseContent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InternalServiceExceptionResponseContent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
