Image:
  Os: alinux2
HeadNode:
  InstanceType: c5.xlarge
  Ssh:
    KeyName: <KEY_NAME>
  Networking:
    SubnetId: <HEAD_SUBNET>
Scheduling:
  Scheduler: plugin
  SchedulerSettings:
    SchedulerDefinition: <PLUGIN_DEFINITION>
#    SchedulerDefinitionS3BucketOwner: <ACCOUNT_ID>
    SchedulerDefinitionChecksum: <PLUGIN_DEFINITION_CHECKSUM>
    GrantSudoPrivileges: true
    CustomSettings:
      CustomKey1: CustomValue1
  SchedulerQueues:
    - Name: queue1
      Networking:
        SubnetIds:
          - <COMPUTE_SUBNET>
      CustomSettings:
        CustomQueueKey1: CustomValue1
      ComputeResources:
        - Name: cr1
          InstanceType: c5.xlarge
          CustomSettings:
            CustomComputeResourceKey1: CustomValue1