Image:
  Os: alinux2
HeadNode:
  InstanceType: c5.2xlarge
  Ssh:
    KeyName: <KEY_NAME>
  Networking:
    SubnetId: <HEAD_SUBNET>
Scheduling:
  Scheduler: plugin
  SchedulerSettings:
    GrantSudoPrivileges: true
    SchedulerDefinition: <PLUGIN_DEFINITION>
    CustomSettings:
      ScaledownIdletime: 10
  SchedulerQueues:
    - Name: queue1
      CapacityType: ONDEMAND
      Networking:
        SubnetIds:
          - <COMPUTE_SUBNET>
      ComputeResources:
        - Name: computeresource1
          InstanceType: c5.xlarge
          MinCount: 1
    - Name: queue2
      CapacityType: SPOT
      Networking:
        SubnetIds:
          - <COMPUTE_SUBNET>
      ComputeResources:
        - Name: computeresource1
          InstanceType: c5.xlarge
