Image:
  Os: alinux2
HeadNode:
  InstanceType: c5.2xlarge
  Ssh:
    KeyName: fdm-jenkins
  Networking:
    SubnetId: subnet-054c929102b5e4c47
Scheduling:
  Scheduler: plugin
  SchedulerSettings:
    GrantSudoPrivileges: true
    SchedulerDefinition: <PLUGIN_DEFINITION>
#    SchedulerDefinitionS3BucketOwner: <ACCOUNT_ID>
    SchedulerDefinitionChecksum: <PLUGIN_DEFINITION_CHECKSUM>
    CustomSettings:
      ScaledownIdletime: 10
  SchedulerQueues:
    - Name: queue1
      CapacityType: ONDEMAND
      Networking:
        SubnetIds:
          - subnet-0a94506a608268ef3
      ComputeResources:
        - Name: computeresource1
          InstanceType: c5.xlarge
          MinCount: 1
    - Name: queue2
      CapacityType: SPOT
      Networking:
        SubnetIds:
          - subnet-0a94506a608268ef3
      ComputeResources:
        - Name: computeresource1
          InstanceType: c5.xlarge
DevSettings:
  AmiSearchFilters:
    Owner: '447714826191'
