# Bump Version workflow that is triggered manually
name: Bump Version for AWSBatch CLI

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      awsbatch-cli-version:
        description: 'The target version of AWSBatch CLI'
        required: true
        type: string
      branch:
        description: 'The Github branch name'
        required: true
        type: string

jobs:
  create-pull-requests:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ inputs.branch }}
    - name: Modifiy Code to Change version
      run: ./util/bump-awsbatch-cli-version.sh ${{ inputs.awsbatch-cli-version }}
        
    - name: Create a Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        commit-message: 'Bump version for awsbatch-cli to ${{ inputs.awsbatch-cli-version }}'
        title: 'Bump version for awsbatch-cli to ${{ inputs.awsbatch-cli-version }}'
        body: |
          This PR contains version bump for awsbatch-cli.
          Auto-generated by Github Action
        branch: versionbumpbatch${{ inputs.branch }}${{ inputs.awsbatch-cli-version }}
        delete-branch: true
        labels: skip-changelog-update
